===========================================================================================
2020-07-02 20:27:49.124  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
SIP/2.0 200 OK
Via: SIP/2.0/TCP 127.0.0.1:62338
Call-ID: 65750151432167il-ed-mara-01
CSeq: 2 SUBSCRIBE
From: sip:jcollier@federationbankia.com
To: <sip:jcollier@federationbankia.com>;tag=12345678
Contact: <sip:216.111.92.37:8443;transport=ssl>;expires=3600;tag=65750151432167il-ed-mara-01__sp3[USCHEQ-ASRTA01.ring2.com]
Expires: 360
Authorization: X-Signed start="1593721668",expire="1593725268",user="jcollier@federationbankia.com",confwiz="my string",nsadrs="il-ed-mara-01.ring2.com",signed="9ecb18b94f0d25fadb4cabe9d469a5fb"
User-Agent: LoopUp eDial ACS 9.1.0b8040
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-last-change: 1593721650
X-Conf_no: 41921
X-recording-enabled: true
X-control-master: jcollier@federationbankia.com
X-subject: Gary Collier's Meeting Room
X-restrict-notify: false
X-no-video: false
X-no-audio: false
X-suppress-system-im: false
X-Route-ID: 2
X-rollcall: disabled
X-Billing-code-required: false
X-start-muted: false
X-Call-URL: true
X-Video-SingleView: 0
X-domain: DEFAULT
Content-Length: 5139
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 134 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv 
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
v=0
o=jcollier@federationbankia.com 1444923171 132 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Dale%20Torpey" (+13194607000) CallByPhone-URL
c=TN RFC2543 +13194607000
t=3802710356 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721542.0
a=leg_no:2
a=remote:216.111.92.36:12114
a=flags:1050146
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:27276
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397548@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Dale%20Torpey
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:681
a=x-ring2-unique_device_id:7574997c-9cc0-4d56-847d-0ef81038321f
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
v=0
o=jcollier@federationbankia.com 1445019609 126 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Tanya" (+13196537120) CallByPhone-URL
c=TN RFC2543 +13196537120
t=3802710447 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721638.0
a=leg_no:4
a=remote:216.111.92.36:12154
a=flags:1050146
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:40694
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397570@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Tanya
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:51156
a=x-ring2-unique_device_id:38d0fccc-116a-4c75-894c-49f33a3c19cd
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
v=0
o=jcollier@federationbankia.com 1445022703 126 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Tim%20swift" (+13194617022) CallByPhone-URL
c=TN RFC2543 +13194617022
t=3802710450 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721642.0
a=leg_no:5
a=remote:216.111.92.36:12174
a=flags:1050146
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:40564
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397572@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Tim%20swift
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:49786
a=x-ring2-unique_device_id:8a169876-64b7-4f70-955a-e252e8d9e2f6
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Call-ID: 65750151432167il-ed-mara-01
CSeq: 1 NOTIFY
From: sip:jcollier@federationbankia.com;tag=12345678
To: sip:jcollier@federationbankia.com
Contact: <sip:216.111.92.37:8443;transport=ssl>;expires=3600;tag=65750151432167il-ed-mara-01__sp3[USCHEQ-ASRTA01.ring2.com]
Expires: 360
Authorization: X-Signed start="1593721668",expire="1593725268",user="jcollier@federationbankia.com",confwiz="my string",nsadrs="il-ed-mara-01.ring2.com",signed="9ecb18b94f0d25fadb4cabe9d469a5fb"
User-Agent: LoopUp eDial ACS 9.1.0b8040
X-NO-TNS: NOTIFY
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-last-change: 1593721650
X-Conf_no: 41921
X-recording-enabled: true
X-control-master: jcollier@federationbankia.com
X-subject: Gary Collier's Meeting Room
X-restrict-notify: false
X-no-video: false
X-no-audio: false
X-suppress-system-im: false
X-Route-ID: 2
X-rollcall: disabled
X-Billing-code-required: false
X-start-muted: false
X-Call-URL: true
X-Video-SingleView: 0
X-domain: DEFAULT
Content-Length: 5139
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 134 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv 
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
v=0
o=jcollier@federationbankia.com 1444923171 132 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Dale%20Torpey" (+13194607000) CallByPhone-URL
c=TN RFC2543 +13194607000
t=3802710356 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721542.0
a=leg_no:2
a=remote:216.111.92.36:12114
a=flags:1050146
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:27276
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397548@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Dale%20Torpey
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:681
a=x-ring2-unique_device_id:7574997c-9cc0-4d56-847d-0ef81038321f
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
v=0
o=jcollier@federationbankia.com 1445019609 126 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Tanya" (+13196537120) CallByPhone-URL
c=TN RFC2543 +13196537120
t=3802710447 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721638.0
a=leg_no:4
a=remote:216.111.92.36:12154
a=flags:1050146
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:40694
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397570@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Tanya
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:51156
a=x-ring2-unique_device_id:38d0fccc-116a-4c75-894c-49f33a3c19cd
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
v=0
o=jcollier@federationbankia.com 1445022703 126 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Tim%20swift" (+13194617022) CallByPhone-URL
c=TN RFC2543 +13194617022
t=3802710450 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721642.0
a=leg_no:5
a=remote:216.111.92.36:12174
a=flags:1050146
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:40564
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397572@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Tim%20swift
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:49786
a=x-ring2-unique_device_id:8a169876-64b7-4f70-955a-e252e8d9e2f6
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:27:49.639  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
SIP/2.0 100 Trying
Via: SIP/2.0/TCP 127.0.0.1:62338
Call-ID: 65750151432167il-ed-mara-01
CSeq: 3 INVITE
Subject: Gary Collier's Meeting Room
From: sip:jcollier@federationbankia.com
To: sip:jcollier@federationbankia.com
Contact: <sip:216.111.92.37:8443;transport=ssl>;expires=3600;tag=65750151432167il-ed-mara-01__sp3[USCHEQ-ASRTA01.ring2.com]
User-Agent: LoopUp eDial ACS 9.1.0b8040
X-Message-Time: 1593721670540996
X-Route-ID: 2
X-recording-enabled: true
X-client-address: 216.111.92.163
X-domain: DEFAULT
uthorization: X-Signed start="1593721669",expire="1593725269",user="jcollier@federationbankia.com",confwiz="my string",nsadrs="il-ed-mara-01.ring2.com",signed="a73789748d9c7dd2d1092794597d2a57"
X-Auto-Record: false
X-Billing-code-required: false
X-dialout: allowed
X-project-code: None
X-subject: Gary Collier's Meeting Room
x-ring2-callowner-login_alias: jcollier@federationbankia.com
x-ring2-callsource: 0
Content-Length: 0

===========================================================================================
2020-07-02 20:27:49.764  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 32 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721670
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 197
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1167
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1445051234 104 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Gary%20Collier" (+13196537112) CallByPhone-URL
c=TN RFC2543 +13196537112
t=3802710470 0
m=audio 1 voice -
a=status:(2) starting
a=mediastatus:sendrecv
a=leg_no:6
a=flags:1054240
a=new_change
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397585@216.111.92.36
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-alt-proj:None
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Gary%20Collier
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:14733
a=x-ring2-unique_device_id:09f7f938-98cb-40ab-be2b-1d1977552bad
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=dialout:click_in
a=access_code:2321360
a=privs:leader
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
===========================================================================================
2020-07-02 20:27:51.577  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 33 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721670
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 197
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-active-talker: 
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1308
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 135 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv active
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=new_change
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:27:56.264  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 34 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-CallEvent: LegAdd
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721677
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 196
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1327
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1445051234 115 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Gary%20Collier" (+13196537112) CallByPhone-URL
c=TN RFC2543 +13196537112
t=3802710477 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721670.0
a=leg_no:6
a=remote:216.111.92.36:12208
a=flags:1054240
a=new_change
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:23744
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397585@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-alt-proj:None
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Gary%20Collier
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:14733
a=x-ring2-unique_device_id:09f7f938-98cb-40ab-be2b-1d1977552bad
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=dialout:click_in
a=access_code:2321360
a=privs:leader
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 35 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721677
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 196
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1327
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1445051234 126 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Gary%20Collier" (+13196537112) CallByPhone-URL
c=TN RFC2543 +13196537112
t=3802710477 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721670.0
a=leg_no:6
a=remote:216.111.92.36:12208
a=flags:1054242
a=new_change
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:23744
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397585@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-alt-proj:None
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Gary%20Collier
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:14733
a=x-ring2-unique_device_id:09f7f938-98cb-40ab-be2b-1d1977552bad
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=dialout:click_in
a=access_code:2321360
a=privs:leader
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:27:58.327  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 36 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721677
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 196
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-active-talker: 
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1301
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 136 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=new_change
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:28:02.452  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 37 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721677
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 197
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-active-talker: 
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1308
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 137 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv active
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=new_change
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:28:03.327  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
SIP/2.0 100 Trying
Via: SIP/2.0/TCP 127.0.0.1:62338
Call-ID: 65750151432167il-ed-mara-01
CSeq: 4 INVITE
Subject: Gary Collier's Meeting Room
From: sip:jcollier@federationbankia.com
To: sip:jcollier@federationbankia.com
Contact: <sip:216.111.92.37:8443;transport=ssl>;expires=3600;tag=65750151432167il-ed-mara-01__sp3[USCHEQ-ASRTA01.ring2.com]
User-Agent: LoopUp eDial ACS 9.1.0b8040
X-Message-Time: 1593721684228957
X-Route-ID: 2
X-recording-enabled: true
X-client-address: 216.111.92.163
X-domain: DEFAULT
uthorization: X-Signed start="1593721683",expire="1593725283",user="jcollier@federationbankia.com",confwiz="my string",nsadrs="il-ed-mara-01.ring2.com",signed="3dadfd7ef8b65962e440984dd3a8cfb8"
X-Auto-Record: false
X-Billing-code-required: false
X-dialout: allowed
X-project-code: None
X-subject: Gary Collier's Meeting Room
x-ring2-callowner-login_alias: jcollier@federationbankia.com
x-ring2-callsource: 0
Content-Length: 0

===========================================================================================
2020-07-02 20:28:03.515  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 38 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721684
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 198
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1141
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1445064890 104 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Mark%20Cobb" (+13196942200) CallByPhone-URL
c=TN RFC2543 +13196942200
t=3802710484 0
m=audio 1 voice -
a=status:(2) starting
a=mediastatus:sendrecv
a=leg_no:7
a=flags:1050144
a=new_change
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397587@216.111.92.36
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Mark%20Cobb
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:53027
a=x-ring2-unique_device_id:b3dfcc29-ea91-434c-b0f6-c1c5770cc7a3
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
===========================================================================================
2020-07-02 20:28:12.327  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 39 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-CallEvent: LegAdd
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721693
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 201
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1301
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1445064890 115 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Mark%20Cobb" (+13196942200) CallByPhone-URL
c=TN RFC2543 +13196942200
t=3802710493 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721684.0
a=leg_no:7
a=remote:216.111.92.36:12210
a=flags:1050144
a=new_change
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:42902
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397587@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Mark%20Cobb
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:53027
a=x-ring2-unique_device_id:b3dfcc29-ea91-434c-b0f6-c1c5770cc7a3
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 40 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721693
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 201
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1301
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1445064890 126 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Mark%20Cobb" (+13196942200) CallByPhone-URL
c=TN RFC2543 +13196942200
t=3802710493 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721684.0
a=leg_no:7
a=remote:216.111.92.36:12210
a=flags:1050146
a=new_change
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:42902
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397587@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Mark%20Cobb
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:53027
a=x-ring2-unique_device_id:b3dfcc29-ea91-434c-b0f6-c1c5770cc7a3
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:28:22.093  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 41 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721693
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 204
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-active-talker: 
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1308
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 138 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv active
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=new_change
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:28:24.968  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 42 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721693
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 204
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-active-talker: 
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1301
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 139 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=new_change
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:28:25.531  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 43 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721693
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 204
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-active-talker: 
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1308
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 140 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv active
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=new_change
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:28:27.843  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 44 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721693
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 205
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-active-talker: 
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1301
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 141 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=new_change
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
===========================================================================================
2020-07-02 20:28:28.218  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 45 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721693
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 205
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-active-talker: 
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 1308
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 142 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv active
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=new_change
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
