===========================================================================================
2020-07-02 20:27:49.014  -- SmartIOGulam() [tid:5016]
---------------------------------------------------------------------------------
SIP/2.0 200 OK
Via: SIP/2.0/TCP 127.0.0.1:62338
Call-ID: 65750151432167il-ed-mara-01
CSeq: 1 REGISTER
From: sip:jcollier@federationbankia.com
To: <sip:jcollier@federationbankia.com>;tag=12345678
Contact: sip:jcollier@federationbankia.com;expires=1593725109;tag=sp2(263988)_IL-PS-CONGO-02.ring2.com,
	 sip:jcollier@federationbankia.com;expires=1593725109;tag=sp2(26392)_IL-PS-CONGO-01.ring2.com,
	 sip:jcollier@federationbankia.com;expires=1593725269;tag=65750151432167il-ed-mara-01__sp3[USCHEQ-ASRTA01.ring2.com]
Authorization: X-Signed start="1593721668",expire="1593725268",user="jcollier@federationbankia.com",confwiz="my string",nsadrs="il-ed-mara-01.ring2.com",signed="9ecb18b94f0d25fadb4cabe9d469a5fb"
User-Agent: LoopUp eDial ACS 9.1.0b8040
X-domain: DEFAULT
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/tcp jcollier@federationbankia.com@federationbankia.com:0
Call-ID: 65750151432167il-ed-mara-01
CSeq: 848352898 SUBSCRIBE
From: sip:jcollier@federationbankia.com
To: <sip:conference.wizard@local.host>;tag=12345678
Contact: <sip:216.111.92.37:8443;transport=ssl>
Authorization: Basic HelloSailor
User-Agent: LoopUp eDial ACS 9.1.0b8052
X-Seamless: SUBSCRIBE
X-domain: DEFAULT
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/TCP 127.0.0.1:62338
Call-ID: 65750151432167il-ed-mara-01
CSeq: 1 REGISTER
From: sip:jcollier@federationbankia.com
To: <sip:jcollier@federationbankia.com>;tag=12345678
Contact: <sip:216.111.92.37:8443;transport=ssl>;expires=3600;tag=65750151432167il-ed-mara-01__sp3[USCHEQ-ASRTA01.ring2.com],
	 
User-Agent: LoopUp eDial ACS 9.1.0b8067
uthorization: X-Signed start="1593721668",expire="1593725268",user="jcollier@federationbankia.com",confwiz="my string",nsadrs="il-ed-mara-01.ring2.com",signed="9ecb18b94f0d25fadb4cabe9d469a5fb"
xpires: 360
X-Seamless: PRESENCE-ALT
X-domain: DEFAULT
Content-Length: 0

