REGISTER sip:subscribe_to_call_events@loopup.com SIP/2.0
Via: SIP/2.0/TCP il-ed-mara-01.ring2.com:8443
To: sip:subscribe_to_call_events@loopup.com
From: sip:subscribe_to_call_events@loopup.com
Call-ID: 8DC1AF9E-8C37-4463-B8C9-1959A1428116
CSeq: 65 REGISTER
Contact: sip:subscribe_to_call_events@loopup.com;expires=300;tag=8176__PMD4-US
Authorization: X-Signed start="1593567777",expire="1593568137",user="subscribe_to_call_events@loopup.com",confwiz="my string",nsadrs="il-ed-mara-01.ring2.com",signed="2c7c7247d66565c8f41985a234b5fe79"
User-Agent: r2ediallib-1.7.1.1/webclient.URL
Content-Type: application/sdp
Expires: 300
X-subscribe-to-leg-events: true
Content-Length: 0

