NOTIFY sip:subscribe_to_call_events@loopup.com;machine SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/UDP localhost:780;branch=akirmayer@sidley.com__eDial_sep__subscribe_to_call_events@loopup.com;received=localhost
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__akirmayer@sidley.com;received=127.0.0.1:57400:1752919488
Via: SIP/2.0/TCP 127.0.0.1:46942;received=127.0.0.1:46942:36406400
Call-ID: 15105076141563il-ed-mara-01
CSeq: 2 NOTIFY
From: sip:conference.wizard@local.host;pool=hk-ed-pearl;box=hk-ed-pearl-01.ring2.com
To: "akirmayer" <sip:akirmayer@sidley.com>
Contact: <sip:localhost:8443;transport=ssl>
X-CallEvent: LegAdd
X-slave-site: localhost
X-last-change: 1593567745
X-drop-with-leader: false
X-Conf_no: 22977
X-no-unmute: false
X-rollcall: disabled
X-Call-URL: true
X-control-master: akirmayer@sidley.com
X-domain: DEFAULT
X-client-address: 127.0.0.1
X-From: akirmayer@sidley.com
X-legs-on-server: 138
X-Sticky: 1
X-rss-id: 
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-leader-required: true
X-Video-UsingMCU: false
X-subject: Asi Kirmayer's Meeting R