SIP/2.0 100 Trying
Via: SIP/2.0/TCP 127.0.0.1:62338
Call-ID: 65750151432167il-ed-mara-01
CSeq: 3 INVITE
Subject: Gary Collier's Meeting Room
From: sip:jcollier@federationbankia.com
To: sip:jcollier@federationbankia.com
Contact: <sip:216.111.92.37:8443;transport=ssl>;expires=3600;tag=65750151432167il-ed-mara-01__sp3[USCHEQ-ASRTA01.ring2.com]
User-Agent: LoopUp eDial ACS 9.1.0b8040
X-Message-Time: 1593721670540996
X-Route-ID: 2
X-recording-enabled: true
X-client-address: 216.111.92.163
X-domain: DEFAULT
uthorization: X-Signed start="1593721669",expire="1593725269",user="jcollier@federationbankia.com",confwiz="my string",nsadrs="il-ed-mara-01.ring2.com",signed="a73789748d9c7dd2d1092794597d2a57"
X-Auto-Record: false
X-Billing-code-required: false
X-dialout: allowed
X-project-code: None
X-subject: Gary Collier's Meeting Room
x-ring2-callowner-login_alias: jcollier@federationbankia.com
x-ring2-callsource: 0
Content-Length: 0
