SIP/2.0 100 Trying
Via: SIP/2.0/TCP 127.0.0.1:62338
Call-ID: 60000000000007aa-aa-aaaa-00
CSeq: 3 INVITE
Subject: Gaaa Caaaaaa'a Maaaaaa Raaa
From: sip:aaaaaaaa@aaaaaaaaaaaaaaaa.com
To: sip:jaaaaaaa@aaaaaaaaaaaaaaaa.com
Contact: <sip:111.111.11.11:8443;transport=ssl>;expires=3600;tag=60000000000007aa-aa-aaaa-00__sp3[aaaaaa-aaaaaa1.ring2.com]
User-Agent: LoopUp eDial ACS 9.1.0b8040
X-Message-Time: 1593721670540996
X-Route-ID: 2
X-recording-enabled: true
X-client-address: 216.111.92.163
X-domain: DEFAULT
uthorization: X-Signed start="1593721669",expire="1593725269",user="jaaaaaaa@aaaaaaaaaaaaaaaa.com",confwiz="my string",nsadrs="aa-aa-aaaa-00.ring2.com",signed="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa7"
X-Auto-Record: false
X-Billing-code-required: false
X-dialout: allowed
X-project-code: None
X-subject: Gaaa Caaaaaa'a Maaaaaa Raaa
x-ring2-callowner-login_alias: jaaaaaaa@aaaaaaaaaaaaaaaa.com
x-ring2-callsource: 0
Content-Length: 0

