trigger:
  batch: true
  branches:
    include:
    - master
    - main
    - bufix/*
    - feature/*
    - hotfix/*
    - release/*
  paths:
    exclude:
    - README.md

pool:
  name: Default
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  buildPlatform: 'x64'
  
steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 6.0.0'
  inputs:
    versionSpec: '6.0.0'
    checkLatest: true

- task: GitVersion@5
  inputs:
    runtime: 'full'
    configFilePath: 'GitVersion.yml'

- script: echo %Action%%BuildVersion%
  displayName: 'Set build version'
  env:
    Action: '##vso[build.updatebuildnumber]'
    BuildVersion: $(GitVersion.NugetVersionV2)

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    vstsFeed: 'a0302836-2c67-4470-bcb5-10149e5447f9'
  continueOnError: true

- task: VSBuild@1
  displayName: 'Build solution sip2json.sln RELEASE'
  inputs:
    solution: 'sip2json.sln'
    platform: 'x64'
    configuration: 'Release'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '$(System.DefaultWorkingDirectory)\test\validation_tests\Release\validation_tests.exe --gtest_output=xml:$(System.DefaultWorkingDirectory)\TestResults'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    resultsFolder: '$(System.DefaultWorkingDirectory)\TestResults'
    runInParallel: true
    codeCoverageEnabled: true
    platform: 'x64'
    configuration: 'Release'


- task: CmdLine@2
  inputs:
    script: |
      echo Running googltest
      cd test
      cd validation_tests
      cd Release
      validation_tests.exe --gtest_output=xml:..\..\..\TestResults\

- task: PublishTestResults@2
  displayName: 'Publish Release Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/validation_tests.xml'
    mergeTestResults: true
    buildPlatform: 'x64'
    buildConfiguration: 'release'
  continueOnError: true

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: 'nuget/SiddiqSoft.sip2json.nuspec;!nuget/SiddiqSoft.sip2json.symbols.nuspec'
    buildProperties: 'VERSION=$(build.buildNumber)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg;build/*.nupkg;!build/*symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'sqs-nuget'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github-packages-sqs'
    repositoryName: 'siddiqsoftware/sip2json'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(build.buildNumber)'
    title: 'v$(build.buildNumber)'
    releaseNotesSource: 'inline'
    isPreRelease: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  
