SIP/2.0 200 OK
Via: SIP/2.0/TCP il-ed-mara-01.ring2.com:8443
Call-ID: 8DC1AF9E-8C37-4463-B8C9-1959A1428116
CSeq: 65 REGISTER
From: sip:subscribe_to_call_events@loopup.com
To: <sip:subscribe_to_call_events@loopup.com>;tag=12345678
Contact: <sip:216.111.92.37:8443;transport=ssl>;expires=300;tag=8176__PMD4-US
Expires: 300
Authorization: X-Signed start="1593567777",expire="1593568137",user="subscribe_to_call_events@loopup.com",confwiz="my string",nsadrs="il-ed-mara-01.ring2.com",signed="2c7c7247d66565c8f41985a234b5fe79"
User-Agent: LoopUp eDial ACS 9.1.0b8067
X-Seamless: PRESENCE-ALT
X-domain: DEFAULT
X-subscribe-to-leg-events: true
Content-Length: 0

