2020-07-28 14:56:31,605631
NOTIFY sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com SIP/2.0
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__jayne.cox@cliffordchance.com;received=127.0.0.1:42938:1442942896
Via: SIP/2.0/TCP 127.0.0.1:38788;received=127.0.0.1:38788:18601584
Call-ID: 58085727726792uk-ed-thames-01
CSeq: 1 NOTIFY
From: sip:conference.wizard@local.host;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
To: sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
Contact: <sip:localhost:8443;transport=ssl>
X-CallEvent: CallStart
X-slave-site: localhost
X-last-change: 1595948191
X-Conf_no: 16732
X-rollcall: disabled
X-Call-URL: true
X-control-master: jayne.cox@cliffordchance.com
X-domain: DEFAULT
X-client-address: 209.3.157.156
X-From: jayne.cox@cliffordchance.com
X-legs-on-server: 232
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-leader-required: true
X-Video-UsingMCU: false
X-subject: Jayne Cox's Meeting Room
X-project-code: None
X-Call-Instance-ID: NTgwODU3Mjc3MjY3OTJ1ay1lZC10aGFtZXMtMDE6MTU5NTk0ODE5MTozODM3MzQ=
X-Route-ID: 1
Content-Length: 1999
Content-type: application/sdp

v=0
o=jayne.cox@cliffordchance.com 909825625 104 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Ian%20Mendoza-Thomas" (+447966297600) CallByPhone-URL
c=TN RFC2543 +447966297600
t=3804936991 0
m=audio 1 voice -
a=status:(2) starting
a=mediastatus:sendrecv
a=leg_no:1
a=flags:1050144
a=new_change
a=server:ukdc1-edm14.ring2.com
a=clir:false:+442036559500
a=acs_guid:000952912930
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jayne.cox@cliffordchance.com
a=legCallid:1409739130@62.189.140.103
a=cdr_start_time:1595948191.546359
a=preferred_identity:+442036559500
a=x-ring2-callowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-legowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Ian%20Mendoza-Thomas
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:89.34.167.72:30522
a=x-ring2-unique_device_id:2037f735-418f-47d9-a2d0-831a9feef965
a=x-ring2-UF1:None
a=ivr:dialout
a=access_code:1467900
a=privs:participant
a=dialout:click_in
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com
v=0
o=jayne.cox@cliffordchance.com 909825421 104 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Jayne%20Cox" (+447881588880) CallByPhone-URL
c=TN RFC2543 +447881588880
t=3804936991 0
m=audio 1 voice -
a=status:(1) pending
a=leg_no:2
a=flags:1054256
a=new_change
a=primary:true
a=server:ukdc1-edm14.ring2.com
a=clir:false:+442036559500
a=acs_guid:000952912930
a=preferred_identity:+442036559500
a=x-ring2-callowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-legowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-alt-proj:None
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jayne%20Cox
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:86.134.65.57:14794
a=x-ring2-unique_device_id:e0078ed6-e93c-45a9-923d-4da1f28c4c7b
a=x-ring2-UF1:None
a=ivr:dialout
a=dialout:click_in
a=access_code:1400916
a=privs:leader
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com


2020-07-28 14:56:31,745779
NOTIFY sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com SIP/2.0
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__jayne.cox@cliffordchance.com;received=127.0.0.1:42938:1442942896
Via: SIP/2.0/TCP 127.0.0.1:38788;received=127.0.0.1:38788:18601584
Call-ID: 58085727726792uk-ed-thames-01
CSeq: 2 NOTIFY
From: sip:conference.wizard@local.host;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
To: sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
Contact: <sip:localhost:8443;transport=ssl>
X-slave-site: localhost
X-last-change: 1595948191
X-Conf_no: 16732
X-rollcall: disabled
X-Call-URL: true
X-control-master: jayne.cox@cliffordchance.com
X-domain: DEFAULT
X-client-address: 209.3.157.156
X-From: jayne.cox@cliffordchance.com
X-legs-on-server: 232
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-leader-required: true
X-Video-UsingMCU: false
X-subject: Jayne Cox's Meeting Room
X-project-code: None
X-Call-Instance-ID: NTgwODU3Mjc3MjY3OTJ1ay1lZC10aGFtZXMtMDE6MTU5NTk0ODE5MTozODM3MzQ=
X-Route-ID: 1
Content-Length: 1099
Content-type: application/sdp

v=0
o=jayne.cox@cliffordchance.com 909825421 105 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Jayne%20Cox" (+447881588880) CallByPhone-URL
c=TN RFC2543 +447881588880
t=3804936991 0
m=audio 1 voice -
a=status:(2) starting
a=mediastatus:sendrecv
a=leg_no:2
a=flags:1054256
a=new_change
a=primary:true
a=server:ukdc1-edm14.ring2.com
a=clir:false:+442036559500
a=acs_guid:000952912930
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jayne.cox@cliffordchance.com
a=legCallid:1409739131@62.189.140.103
a=cdr_start_time:1595948191.649910
a=preferred_identity:+442036559500
a=x-ring2-callowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-legowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-alt-proj:None
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jayne%20Cox
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:86.134.65.57:14794
a=x-ring2-unique_device_id:e0078ed6-e93c-45a9-923d-4da1f28c4c7b
a=x-ring2-UF1:None
a=ivr:dialout
a=dialout:click_in
a=access_code:1400916
a=privs:leader
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com


2020-07-28 14:56:40,334715
NOTIFY sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com SIP/2.0
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__jayne.cox@cliffordchance.com;received=127.0.0.1:42938:1442942896
Via: SIP/2.0/TCP 127.0.0.1:38788;received=127.0.0.1:38788:18601584
Call-ID: 58085727726792uk-ed-thames-01
CSeq: 5 NOTIFY
From: sip:conference.wizard@local.host;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
To: sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
Contact: <sip:localhost:8443;transport=ssl>
X-CallEvent: LegAdd
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1595948200
X-Conf_no: 16732
X-rollcall: disabled
X-Call-URL: true
X-control-master: jayne.cox@cliffordchance.com
X-domain: DEFAULT
X-client-address: 209.3.157.156
X-From: jayne.cox@cliffordchance.com
X-legs-on-server: 237
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-leader-required: true
X-Video-UsingMCU: false
X-subject: Jayne Cox's Meeting Room
X-project-code: None
X-Call-Instance-ID: NTgwODU3Mjc3MjY3OTJ1ay1lZC10aGFtZXMtMDE6MTU5NTk0ODE5MTozODM3MzQ=
X-Route-ID: 1
Content-Length: 1219
Content-type: application/sdp

v=0
o=jayne.cox@cliffordchance.com 909825421 116 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Jayne%20Cox" (+447881588880) CallByPhone-URL
c=TN RFC2543 +447881588880
t=3804936991 0
m=audio 1 voice -
a=status:(203) answered
a=mediastatus:sendrecv
a=leg_no:2
a=remote:62.189.140.103:12130
a=flags:1054256
a=new_change
a=primary:true
a=server:ukdc1-edm14.ring2.com
a=clir:false:+442036559500
a=far_end:62.189.140.124:34730
a=acs_guid:000952912930
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jayne.cox@cliffordchance.com
a=legCallid:1409739131@62.189.140.103
a=audio_payload:PCMA
a=cdr_start_time:1595948191.649910
a=preferred_identity:+442036559500
a=x-ring2-callowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-legowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-alt-proj:None
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jayne%20Cox
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:86.134.65.57:14794
a=x-ring2-unique_device_id:e0078ed6-e93c-45a9-923d-4da1f28c4c7b
a=x-ring2-UF1:None
a=ivr:dialout
a=dialout:click_in
a=access_code:1400916
a=privs:leader
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com
a=user-agent:BN4000-3.8.1-850


2020-07-28 14:56:40,335357
NOTIFY sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com SIP/2.0
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__jayne.cox@cliffordchance.com;received=127.0.0.1:42938:1442942896
Via: SIP/2.0/TCP 127.0.0.1:38788;received=127.0.0.1:38788:18601584
Call-ID: 58085727726792uk-ed-thames-01
CSeq: 6 NOTIFY
From: sip:conference.wizard@local.host;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
To: sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1595948200
X-Conf_no: 16732
X-rollcall: disabled
X-Call-URL: true
X-control-master: jayne.cox@cliffordchance.com
X-domain: DEFAULT
X-client-address: 209.3.157.156
X-From: jayne.cox@cliffordchance.com
X-legs-on-server: 237
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-leader-required: true
X-Video-UsingMCU: false
X-subject: Jayne Cox's Meeting Room
X-project-code: None
X-Call-Instance-ID: NTgwODU3Mjc3MjY3OTJ1ay1lZC10aGFtZXMtMDE6MTU5NTk0ODE5MTozODM3MzQ=
X-Route-ID: 1
Content-Length: 1197
Content-type: application/sdp

v=0
o=jayne.cox@cliffordchance.com 909825625 105 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Ian%20Mendoza-Thomas" (+447966297600) CallByPhone-URL
c=TN RFC2543 +447966297600
t=3804936991 0
m=audio 1 voice -
a=status:(2) starting
a=mediastatus:sendrecv
a=leg_no:1
a=remote:62.189.140.103:12062
a=flags:1050144
a=new_change
a=server:ukdc1-edm14.ring2.com
a=clir:false:+442036559500
a=far_end:62.189.140.124:63906
a=acs_guid:000952912930
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jayne.cox@cliffordchance.com
a=legCallid:1409739130@62.189.140.103
a=audio_payload:PCMA
a=cdr_start_time:1595948191.546359
a=preferred_identity:+442036559500
a=x-ring2-callowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-legowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Ian%20Mendoza-Thomas
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:89.34.167.72:30522
a=x-ring2-unique_device_id:2037f735-418f-47d9-a2d0-831a9feef965
a=x-ring2-UF1:None
a=ivr:dialout
a=access_code:1467900
a=privs:participant
a=dialout:click_in
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com
a=user-agent:BN4000-3.8.1-850


2020-07-28 14:56:48,000360
NOTIFY sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com SIP/2.0
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__jayne.cox@cliffordchance.com;received=127.0.0.1:42938:1442942896
Via: SIP/2.0/TCP 127.0.0.1:38788;received=127.0.0.1:38788:18601584
Call-ID: 58085727726792uk-ed-thames-01
CSeq: 8 NOTIFY
From: sip:conference.wizard@local.host;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
To: sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
Contact: <sip:localhost:8443;transport=ssl>
X-CallEvent: LegDrop
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1595948208
X-Conf_no: 16732
X-rollcall: disabled
X-Call-URL: true
X-control-master: jayne.cox@cliffordchance.com
X-domain: DEFAULT
X-client-address: 209.3.157.156
X-From: jayne.cox@cliffordchance.com
X-legs-on-server: 240
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-leader-required: true
X-Video-UsingMCU: false
X-subject: Jayne Cox's Meeting Room
X-project-code: None
X-Call-Instance-ID: NTgwODU3Mjc3MjY3OTJ1ay1lZC10aGFtZXMtMDE6MTU5NTk0ODE5MTozODM3MzQ=
X-Route-ID: 1
Content-Length: 1326
Content-type: application/sdp

v=0
o=jayne.cox@cliffordchance.com 909825625 116 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Ian%20Mendoza-Thomas" (+447966297600) CallByPhone-URL
c=TN RFC2543 +447966297600
t=3804936991 3804937008
m=audio 1 voice -
a=status:(4) dropped
a=mediastatus:sendrecv
a=cause: (20001) Normal Hangup - Received SIP BYE From: A447966297600@62.189.140.124
a=leg_no:1
a=remote:62.189.140.103:12062
a=flags:1050144
a=new_change
a=server:ukdc1-edm14.ring2.com
a=clir:false:+442036559500
a=far_end:62.189.140.124:63906
a=acs_guid:000952912930
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jayne.cox@cliffordchance.com
a=legCallid:1409739130@62.189.140.103
a=audio_payload:PCMA
a=cdr_start_time:1595948191.546359
a=preferred_identity:+442036559500
a=x-ring2-callowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-legowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Ian%20Mendoza-Thomas
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:89.34.167.72:30522
a=x-ring2-unique_device_id:2037f735-418f-47d9-a2d0-831a9feef965
a=x-ring2-UF1:None
a=ivr:dialout
a=access_code:1467900
a=privs:participant
a=dialout:click_in
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com
a=user-agent:BN4000-3.8.1-850
a=cdr_stop_time:1595948208.999480


2020-07-28 14:56:49,285458
NOTIFY sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com SIP/2.0
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__jayne.cox@cliffordchance.com;received=127.0.0.1:42938:1442942896
Via: SIP/2.0/TCP 127.0.0.1:38788;received=127.0.0.1:38788:18601584
Call-ID: 58085727726792uk-ed-thames-01
CSeq: 1 NOTIFY
From: sip:conference.wizard@local.host;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
To: sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
Contact: <sip:localhost:8443;transport=ssl>
X-CallEvent: LegDrop
X-remote-leader: true
X-slave-site: localhost
X-Call-Instance-ID: NTgwODU3Mjc3MjY3OTJ1ay1lZC10aGFtZXMtMDE6MTU5NTk0ODE5MTozODM3MzQ=
X-last-change: 1595948209
X-Conf_no: 16732
X-recording-enabled: true
X-subject: Jayne Cox's Meeting Room
X-rollcall: disabled
X-Call-URL: true
X-control-master: jayne.cox@cliffordchance.com
X-domain: DEFAULT
X-client-address: 209.3.157.156
X-From: jayne.cox@cliffordchance.com
X-legs-on-server: 240
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-Billing-code-required: false
X-Video-UsingMCU: false
X-Route-ID: 1
Content-Length: 615
Content-type: application/sdp

v=0
o=jayne.cox@cliffordchance.com 909825625 217 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Ian%20Mendoza-Thomas" (447966297600) CallByPhone-URL
c=TN RFC2543 447966297600
t=2208988801 3804937009
m=audio 1 voice -
a=status:(4) dropped
a=leg_no:1
a=flags:1180192
a=new_change
a=server:ukdc1-edm14.ring2.com
a=clir:false
a=x-ring2-displayname:Ian%20Mendoza-Thomas
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:89.34.167.72:30522
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com
a=x-ring2-unique_device_id:2037f735-418f-47d9-a2d0-831a9feef965
a=cdr_stop_time:1595948209.284676


2020-07-28 14:57:05,350850
NOTIFY sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com SIP/2.0
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__jayne.cox@cliffordchance.com;received=127.0.0.1:42938:1442942896
Via: SIP/2.0/TCP 127.0.0.1:38788;received=127.0.0.1:38788:18601584
Call-ID: 58085727726792uk-ed-thames-01
CSeq: 9 NOTIFY
From: sip:conference.wizard@local.host;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
To: sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1595948225
X-Conf_no: 16732
X-rollcall: disabled
X-Call-URL: true
X-control-master: jayne.cox@cliffordchance.com
X-domain: DEFAULT
X-client-address: 209.3.157.156
X-From: jayne.cox@cliffordchance.com
X-legs-on-server: 245
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-leader-required: true
X-Video-UsingMCU: false
X-subject: Jayne Cox's Meeting Room
X-project-code: None
X-Call-Instance-ID: NTgwODU3Mjc3MjY3OTJ1ay1lZC10aGFtZXMtMDE6MTU5NTk0ODE5MTozODM3MzQ=
X-Route-ID: 1
Content-Length: 1081
Content-type: application/sdp

v=0
o=jayne.cox@cliffordchance.com 909859906 104 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Ian%20Mendoza-Thomas" (+447966297600) CallByPhone-URL
c=TN RFC2543 +447966297600
t=3804937025 0
m=audio 1 voice -
a=status:(2) starting
a=mediastatus:sendrecv
a=leg_no:3
a=flags:1050144
a=new_change
a=server:ukdc1-edm14.ring2.com
a=clir:false:+442036559500
a=acs_guid:000952912930
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jayne.cox@cliffordchance.com
a=legCallid:1409739147@62.189.140.103
a=cdr_start_time:1595948225.207703
a=preferred_identity:+442036559500
a=x-ring2-callowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-legowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Ian%20Mendoza-Thomas
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:89.34.167.72:30522
a=x-ring2-unique_device_id:2037f735-418f-47d9-a2d0-831a9feef965
a=x-ring2-UF1:None
a=ivr:dialout
a=access_code:1467900
a=privs:participant
a=dialout:click_in
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com


2020-07-28 14:57:14,136189
NOTIFY sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com SIP/2.0
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__jayne.cox@cliffordchance.com;received=127.0.0.1:42938:1442942896
Via: SIP/2.0/TCP 127.0.0.1:38788;received=127.0.0.1:38788:18601584
Call-ID: 58085727726792uk-ed-thames-01
CSeq: 10 NOTIFY
From: sip:conference.wizard@local.host;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
To: sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
Contact: <sip:localhost:8443;transport=ssl>
X-CallEvent: LegAdd
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1595948234
X-Conf_no: 16732
X-rollcall: disabled
X-Call-URL: true
X-control-master: jayne.cox@cliffordchance.com
X-domain: DEFAULT
X-client-address: 209.3.157.156
X-From: jayne.cox@cliffordchance.com
X-legs-on-server: 245
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-leader-required: true
X-Video-UsingMCU: false
X-subject: Jayne Cox's Meeting Room
X-project-code: None
X-Call-Instance-ID: NTgwODU3Mjc3MjY3OTJ1ay1lZC10aGFtZXMtMDE6MTU5NTk0ODE5MTozODM3MzQ=
X-Route-ID: 1
Content-Length: 1201
Content-type: application/sdp

v=0
o=jayne.cox@cliffordchance.com 909859906 115 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Ian%20Mendoza-Thomas" (+447966297600) CallByPhone-URL
c=TN RFC2543 +447966297600
t=3804937025 0
m=audio 1 voice -
a=status:(203) answered
a=mediastatus:sendrecv
a=leg_no:3
a=remote:62.189.140.103:12282
a=flags:1050144
a=new_change
a=server:ukdc1-edm14.ring2.com
a=clir:false:+442036559500
a=far_end:62.189.140.124:14628
a=acs_guid:000952912930
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jayne.cox@cliffordchance.com
a=legCallid:1409739147@62.189.140.103
a=audio_payload:PCMA
a=cdr_start_time:1595948225.207703
a=preferred_identity:+442036559500
a=x-ring2-callowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-legowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Ian%20Mendoza-Thomas
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:89.34.167.72:30522
a=x-ring2-unique_device_id:2037f735-418f-47d9-a2d0-831a9feef965
a=x-ring2-UF1:None
a=ivr:dialout
a=access_code:1467900
a=privs:participant
a=dialout:click_in
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com
a=user-agent:BN4000-3.8.1-850


2020-07-28 15:16:03,889217
NOTIFY sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com SIP/2.0
Via: SIP/2.0/TCP localhost:780;branch=conference.wizard@local.host__eDial_sep__jayne.cox@cliffordchance.com;received=127.0.0.1:42938:1442942896
Via: SIP/2.0/TCP 127.0.0.1:38788;received=127.0.0.1:38788:18601584
Call-ID: 58085727726792uk-ed-thames-01
CSeq: 12 NOTIFY
From: sip:conference.wizard@local.host;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
To: sip:jayne.cox@cliffordchance.com;pool=uk-ed-thames;box=ukdc1-edm14.ring2.com
Contact: <sip:localhost:8443;transport=ssl>
X-CallEvent: LegDrop
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1595949363
X-Conf_no: 16732
X-rollcall: disabled
X-Call-URL: true
X-control-master: jayne.cox@cliffordchance.com
X-domain: DEFAULT
X-client-address: 209.3.157.156
X-From: jayne.cox@cliffordchance.com
X-legs-on-server: 320
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-leader-required: true
X-Video-UsingMCU: false
X-subject: Jayne Cox's Meeting Room
X-project-code: None
X-Call-Instance-ID: NTgwODU3Mjc3MjY3OTJ1ay1lZC10aGFtZXMtMDE6MTU5NTk0ODE5MTozODM3MzQ=
X-Route-ID: 1
Content-Length: 1326
Content-type: application/sdp

v=0
o=jayne.cox@cliffordchance.com 909859906 137 IN IP4 uk-ed-thames-01.ring2.com
s=Jayne Cox's Meeting Room
i="Ian%20Mendoza-Thomas" (+447966297600) CallByPhone-URL
c=TN RFC2543 +447966297600
t=3804937025 3804938163
m=audio 1 voice -
a=status:(4) dropped
a=mediastatus:sendrecv
a=cause: (20001) Normal Hangup - Received SIP BYE From: A447966297600@62.189.140.124
a=leg_no:3
a=remote:62.189.140.103:12282
a=flags:1050146
a=new_change
a=server:ukdc1-edm14.ring2.com
a=clir:false:+442036559500
a=far_end:62.189.140.124:14628
a=acs_guid:000952912930
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jayne.cox@cliffordchance.com
a=legCallid:1409739147@62.189.140.103
a=audio_payload:PCMA
a=cdr_start_time:1595948225.207703
a=preferred_identity:+442036559500
a=x-ring2-callowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-legowner-login_alias:jayne.cox@cliffordchance.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Ian%20Mendoza-Thomas
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:89.34.167.72:30522
a=x-ring2-unique_device_id:2037f735-418f-47d9-a2d0-831a9feef965
a=x-ring2-UF1:None
a=ivr:dialout
a=access_code:1467900
a=privs:participant
a=dialout:click_in
a=x-ring2-smartproxy:usdc2-asalt04.ring2.com
a=user-agent:BN4000-3.8.1-850
a=cdr_stop_time:1595949363.888498
