NOTIFY sip:jcollier@federationbankia.com SIP/2.0
Via: SIP/2.0/tcp localhost:8443
Via: SIP/2.0/tcp localhost:8443;branch=jcollier@federationbankia.com__eDial_sep__jcollier@federationbankia.com
Call-ID: 65750151432167il-ed-mara-01
CSeq: 31 NOTIFY
From: sip:jcollier@federationbankia.com;pool=il-ed-mara;box=il-ed-mara-06.ring2.com;tag=12345678
To: "jcollier" <sip:jcollier@federationbankia.com>
Contact: <sip:localhost:8443;transport=ssl>
X-remote-leader: true
X-slave-site: localhost
X-last-change: 1593721650
X-Conf_no: 41921
X-rollcall: disabled
X-Call-URL: true
Warning: X-200 From SUBSCRIBE
X-control-master: jcollier@federationbankia.com
X-domain: DEFAULT
X-client-address: 216.111.92.163
X-From: jcollier@federationbankia.com
X-legs-on-server: 196
X-start-muted: false
X-Video-SingleView: 0
X-suppress-system-im: false
X-restrict-notify: false
X-notify-im: false
X-no-audio: false
X-no-video: false
X-dialout: allowed
X-Billing-code-required: false
X-recording-enabled: true
X-Video-UsingMCU: false
X-subject: Gary Collier's Meeting Room
X-project-code: None
X-department-code: retail:USA
X-Call-Instance-ID: NjU3NTAxNTE0MzIxNjdpbC1lZC1tYXJhLTAxOjE1OTM3MjE1MDg6NDExMDQ0
X-Route-ID: 2
X-Call-Start-Time: 1593721508.411058
Content-Length: 5139
Content-type: application/sdp

v=0
o=jcollier@federationbankia.com 1444888750 134 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Jim" (+13194617917) CallByPhone-URL
c=TN RFC2543 +13194617917
t=3802710347 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv 
a=cdr_start_time:1593721508.0
a=leg_no:1
a=remote:216.111.92.36:12058
a=flags:1050162
a=primary:true
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:41488
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397542@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Jim
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:39941
a=x-ring2-unique_device_id:3c4cd569-bd06-4d32-b9a0-3d282371200d
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
v=0
o=jcollier@federationbankia.com 1444923171 132 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Dale%20Torpey" (+13194607000) CallByPhone-URL
c=TN RFC2543 +13194607000
t=3802710356 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721542.0
a=leg_no:2
a=remote:216.111.92.36:12114
a=flags:1050146
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:27276
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397548@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Dale%20Torpey
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:681
a=x-ring2-unique_device_id:7574997c-9cc0-4d56-847d-0ef81038321f
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
v=0
o=jcollier@federationbankia.com 1445019609 126 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Tanya" (+13196537120) CallByPhone-URL
c=TN RFC2543 +13196537120
t=3802710447 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721638.0
a=leg_no:4
a=remote:216.111.92.36:12154
a=flags:1050146
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:40694
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397570@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Tanya
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:51156
a=x-ring2-unique_device_id:38d0fccc-116a-4c75-894c-49f33a3c19cd
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
v=0
o=jcollier@federationbankia.com 1445022703 126 IN IP4 il-ed-mara-01.ring2.com
s=Gary Collier's Meeting Room
i="Tim%20swift" (+13194617022) CallByPhone-URL
c=TN RFC2543 +13194617022
t=3802710450 0
m=audio 1 voice -
a=status:(203) answered  
a=mediastatus:sendrecv
a=cdr_start_time:1593721642.0
a=leg_no:5
a=remote:216.111.92.36:12174
a=flags:1050146
a=server:il-ed-mara-06.ring2.com
a=clir:false:3122332580
a=far_end:216.111.92.73:40564
a=acs_guid:001367321370
a=cli-screening:00
a=trunk:8:chan:0
a=useforfrom:jcollier@federationbankia.com
a=legCallid:646397572@216.111.92.36
a=audio_payload:PCMU
a=preferred_identity:3122332580
a=x-ring2-callowner-login_alias:jcollier@federationbankia.com
a=x-ring2-legowner-login_alias:jcollier@federationbankia.com
a=x-ring2-call_source_type:0
a=x-ring2-displayname:Tim%20swift
a=x-ring2-displayname_type:0
a=x-ring2-clientaddress:216.111.92.222:49786
a=x-ring2-unique_device_id:8a169876-64b7-4f70-955a-e252e8d9e2f6
a=x-ring2-UF1:None
a=ivr:dialout-confirm
a=access_code:2768465
a=privs:participant
a=dialout:click_in
a=x-ring2-LICENSE_URI:urn:object:r2license:user:com.ring2.consumer:7BF150F5-5230-4946-B3DA-66337993A01B
a=x-ring2-smartproxy:USCHEQ-ASRTA01.ring2.com
a=user-agent:Cisco-SIPGateway/IOS-16.3.3
