SIP/2.0 401 Unauthorized
Via: SIP/2.0/TCP il-ed-aras-01.ring2-corp.com:8443
Call-ID: 755a8c07-ee3c-43fd-bfb-7f93ade4-89aaab98a8bb
CSeq: 1 REGISTER
From: sip:no_such_user_exists@loopup.com
To: <sip:no_such_user_exists@loopup.com>;tag=12345678
Contact: <sip:67.131.238.71:8443;transport=ssl>;expires=360;tag=14084__fenway.ring2-corp.com
Expires: 360
Authorization: X-Signed start="1595022925",expire="1595023285",user="no_such_user_exists@loopup.com",confwiz="my string",nsadrs="il-ed-aras-01.ring2-corp.com",signed="1d588b59eead861962c7b0d3a8ff147b"
User-Agent: LoopUp eDial ACS 9.1.0b8071
WWW-Authenticate: Basic realm=eDial
X-domain: DEFAULT
Date: Fri, 17 Jul 2020 21:55:25 GMT
Content-Length: 0

