SIP/2.0 100 Trying
Via: SIP/2.0/TCP 127.0.0.1:62338
Call-ID: callid002200000000000000000
CSeq: 3 INVITE
Subject: Gaaa Caaaaaa'a Maaaaaa Raaa
From: sip:aaaaaaaa@aaaaaaaaaaaaaaaa.com
To: sip:jaaaaaaa@aaaaaaaaaaaaaaaa.com
Contact: <sip:192.0.2.4:8443;transport=ssl>;expires=3600;tag=callid002200000000000000000__sp3[aaaaaa-aaaaaa1.example.net]
User-Agent: Example eDial ACS 9.1.0b8040
X-Message-Time: 1593721670540996
X-Route-ID: 2
X-recording-enabled: true
X-client-address: 192.0.2.163
X-domain: DEFAULT
uthorization: X-Signed start="1593721669",expire="1593725269",user="jaaaaaaa@aaaaaaaaaaaaaaaa.com",confwiz="my string",nsadrs="aa-aa-aaaa-00.example.net",signed="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa7"
X-Auto-Record: false
X-Billing-code-required: false
X-dialout: allowed
X-project-code: None
X-subject: Gaaa Caaaaaa'a Maaaaaa Raaa
x-ring2-callowner-login_alias: jaaaaaaa@aaaaaaaaaaaaaaaa.com
x-ring2-callsource: 0
Content-Length: 0

